2022-07-10 03:16:04,513 - INFO - Beginning execution of remove_N_from_fastq.py in directory /u/project/ngarud/jonmah/demo_for_ccgb/Scripts

2022-07-10 03:16:04,513 - INFO - Progress is being logged to ../Data/oral_microbiome_data/fastq_MIDAS_intermediate/SRS149581/compute_pi.log

2022-07-10 03:16:04,513 - INFO - Parsed the following arguments:
	input_fastq_gz = ../Data/oral_microbiome_data/fastq_MIDAS_intermediate/SRS149581/SRS149581.denovo_duplicates_marked.trimmed.1.fastq.gz
	output_fastq_gz = ../Data/oral_microbiome_data/fastq_MIDAS_intermediate/SRS149581/removed_SRS149581.denovo_duplicates_marked.trimmed.1.fastq.gz
	outprefix = ../Data/oral_microbiome_data/fastq_MIDAS_intermediate/SRS149581/

MemoryError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/u/project/ngarud/jonmah/demo_for_ccgb/Scripts/remove_N_from_fastq.py", line 142, in <module>
    removeNs().main()
  File "/u/project/ngarud/jonmah/demo_for_ccgb/Scripts/remove_N_from_fastq.py", line 120, in main
    lines = input.readlines()
MemoryError
2022-07-10 03:19:58,423 - INFO - Beginning execution of remove_N_from_fastq.py in directory /u/project/ngarud/jonmah/demo_for_ccgb/Scripts

2022-07-10 03:19:58,423 - INFO - Progress is being logged to ../Data/oral_microbiome_data/fastq_MIDAS_intermediate/SRS149581/compute_pi.log

2022-07-10 03:19:58,423 - INFO - Parsed the following arguments:
	input_fastq_gz = ../Data/oral_microbiome_data/fastq_MIDAS_intermediate/SRS149581/SRS149581.denovo_duplicates_marked.trimmed.2.fastq.gz
	output_fastq_gz = ../Data/oral_microbiome_data/fastq_MIDAS_intermediate/SRS149581/removed_SRS149581.denovo_duplicates_marked.trimmed.2.fastq.gz
	outprefix = ../Data/oral_microbiome_data/fastq_MIDAS_intermediate/SRS149581/

Traceback (most recent call last):
  File "/u/project/ngarud/jonmah/demo_for_ccgb/Scripts/remove_N_from_fastq.py", line 142, in <module>
    removeNs().main()
  File "/u/project/ngarud/jonmah/demo_for_ccgb/Scripts/remove_N_from_fastq.py", line 120, in main
    lines = input.readlines()
  File "/u/home/j/jonmah/project-ngarud/miniconda3/envs/py3/lib/python3.10/gzip.py", line 399, in readline
    return self._buffer.readline(size)
  File "/u/home/j/jonmah/project-ngarud/miniconda3/envs/py3/lib/python3.10/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/u/home/j/jonmah/project-ngarud/miniconda3/envs/py3/lib/python3.10/gzip.py", line 496, in read
    uncompress = self._decompressor.decompress(buf, size)
MemoryError
